const RouterActionTypes = {
  SEND_COMMAND_START: "SEND_COMMAND_START",
  SEND_COMMAND_SUCCESS: "SEND_COMMAND_SUCCESS",
  SEND_COMMAND_FAILURE: "SEND_COMMAND_FAILURE",
  SEND_OSPF_CONFIG_START: "SEND_OSPF_CONFIG_START",
  SEND_OSPF_CONFIG_SUCCESS: "SEND_OSPF_CONFIG_SUCCESS",
  SEND_OSPF_CONFIG_FAILURE: "SEND_OSPF_CONFIG_FAILURE",
  GET_TOPOLOGY_START: "GET_TOPOLOGY_START",
  GET_TOPOLOGY_SUCCESS: "GET_TOPOLOGY_SUCCESS",
  GET_TOPOLOGY_FAILURE: "GET_TOPOLOGY_FAILURE",
};

export default RouterActionTypes;
