"""
Django settings for zero_backend project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

from flask_cors import cross_origin
import mongoengine
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-ddza%bcexs%$s)%g71@izmd*pb0ni^m)=(lox-n5t$b)ai%*lh"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_filters",
    "rest_framework",
    "zero_touch_api",
    "corsheaders",
    # "mongoengine.django.mongo_auth"
    # "mongo_auth.MongoUser"
    # "debug_toolbar",
]

# AUTH_USER_MODEL = "mongo_auth.MongoUser"


MIDDLEWARE = [
    # "debug_toolbar.middleware.DebugToolbarMiddleware"
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

INTERNAL_IPS = ["127.0.0.1"]


CORS_ALLOW_ALL_ORIGINS = True

# CORS_ALLOWED_ORIGINS = [

# ]

# CORS_ORIGIN_ALLOW_ALL = True


ROOT_URLCONF = "zero_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "zero_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }
# DATABASES = {}
DATABASES = {
    "default": {
        "ENGINE": "djongo",
        "NAME": "zeroTouchDB",
    }
}
# DATABASES = {"default": {"ENGINE": "django.db.backends.dummy"}}

# load_dotenv(dotenv_path="./.env.local")

# MONGO_URL = os.environ.get("MONGO_URL", "mongo")
# MONGO_USERNAME = os.environ.get("MONGO_USERNAME", "root")
# MONGO_PASSWORD = os.environ.get("MONGO_PASSWORD", "")
# MONGO_PORT = os.environ.get("MONGO_PORT", 27017)

# mongoengine.connect(
#     db="zeroTouchDB",
#     # username=MONGO_USERNAME,
#     # password=MONGO_PASSWORD,
# )


# AUTHENTICATION_BACKENDS = ("mongoengine.django.auth.MongoEngineBackend",)
# AUTH_USER_MODEL = "mongo_auth.MongoUser"

# AUTHENTICATION_BACKENDS = ("mongoengine.django.auth.MongoEngineBackend",)
# MONGOENGINE_USER_DOCUMENT = "mongoengine.django.auth.User"
# AUTH_USER_MODEL = "mongo_auth.MongoUser"

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # noqa
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# AUTHENTICATION_BACKENDS = ("mongoengine.django.auth.MongoEngineBackend",)


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
