# Generated by Django 4.0.5 on 2022-07-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zero_touch_api', '0002_zerotouch_network'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zerotouch',
            old_name='ip',
            new_name='IP',
        ),
    ]
