# Generated by Django 4.1 on 2022-08-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zero_touch_api", "0003_rename_ip_zerotouch_ip"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ZeroTouch",
        ),
    ]
