# Generated by Django 4.1.1 on 2022-09-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("zero_touch_api", "0004_delete_zerotouch"),
    ]

    operations = [
        migrations.CreateModel(
            name="Field",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("label", models.CharField(max_length=50)),
                ("imageUrl", models.CharField(max_length=6000)),
                (
                    "status",
                    models.CharField(
                        choices=[("F", "fixed"), ("R", "")], default="R", max_length=50
                    ),
                ),
                ("isDropdown", models.BooleanField()),
            ],
        ),
    ]
