genie_parsers = [
    "show interfaces",
    "show interfaces accounting",
    "show interfaces description",
    "show interfaces stats",
    "show interfaces status",
    "show interfaces switchport",
    "show interfaces transceiver",
    "show interfaces transceiver detail",
    "show interfaces trunk",
    "show interfaces {{interface}}",
    "show interfaces {{interface}} accounting",
    "show interfaces {{interface}} counters",
    "show interfaces {{interface}} description",
    "show interfaces {{interface}} stats",
    "show interfaces {{interface}} status",
    "show interfaces {{interface}} switchport",
    "show interfaces {{interface}} transceiver",
    "show interfaces {{interface}} transceiver detail",
    "show inventory",
    "show ip arp",
    "show ip arp summary",
    "show ip arp vrf {{vrf}}",
    "show ip arp vrf {{vrf}} {{intf_or_ip}}",
    "show ip arp {{intf_or_ip}}",
    "show ip bgp",
    "show ip bgp all dampening parameters",
    "show ip bgp regexp {{regexp}}",
    "show ip bgp template peer-policy",
    "show ip bgp template peer-policy {{template_name}}",
    "show ip bgp template peer-session",
    "show ip bgp template peer-session {{template_name}}",
    "show ip bgp {{address_family}} rd {{rd}}",
    "show ip bgp {{address_family}} vrf {{vrf}}",
    "show ip eigrp interfaces",
    "show ip eigrp interfaces detail",
    "show ip eigrp neighbors",
    "show ip eigrp neighbors detail",
    "show ip eigrp vrf {{vrf}} interfaces",
    "show ip eigrp vrf {{vrf}} neighbors",
    "show ip eigrp vrf {{vrf}} neighbors detail",
    "show ip igmp groups detail",
    "show ip igmp interface",
    "show ip igmp ssm-mapping {{group}}",
    "show ip igmp vrf {{vrf}} groups detail",
    "show ip igmp vrf {{vrf}} interface",
    "show ip igmp vrf {{vrf}} ssm-mapping {{group}}",
    "show ip interface",
    "show ip interface brief",
    "show ip interface brief {{interface}}",
    "show ip interface brief | include Vlan",
    "show ip interface brief | include {{ip}}",
    "show ip interface {{interface}}",
    "show ip mroute",
    "show ip mroute static",
    "show ip mroute vrf {{vrf}}",
    "show ip mroute vrf {{vrf}} static",
    "show ip mroute vrf {{vrf}} {{group}}",
    "show ip mroute vrf {{vrf}} {{group}} {{source}}",
    "show ip mroute vrf {{vrf}} {{group}} {{source}} {{verbose}}",
    "show ip mroute vrf {{vrf}} {{group}} {{verbose}}",
    "show ip mroute vrf {{vrf}} {{verbose}}",
    "show ip mroute {{group}}",
    "show ip mroute {{group}} {{source}}",
    "show ip mroute {{group}} {{source}} {{verbose}}",
    "show ip mroute {{group}} {{verbose}}",
    "show ip mroute {{verbose}}",
    "show ip msdp peer",
    "show ip msdp sa-cache",
    "show ip msdp vrf {{vrf}} peer",
    "show ip msdp vrf {{vrf}} sa-cache",
    "show ip multicast",
    "show ip multicast vrf {{vrf}}",
    "show ip nat statistics",
    "show ip nat translations",
    "show ip nat translations verbose",
    "show ip nat translations vrf {{vrf}}",
    "show ip nat translations vrf {{vrf}} verbose",
    "show ip ospf",
    "show ip ospf database external",
    "show ip ospf database network",
    "show ip ospf database opaque-area",
    "show ip ospf database router",
    "show ip ospf database summary",
    "show ip ospf interface",
    "show ip ospf interface {{interface}}",
    "show ip ospf mpls ldp interface",
    "show ip ospf mpls ldp interface {{interface}}",
    "show ip ospf mpls traffic-eng link",
    "show ip ospf neighbor detail",
    "show ip ospf neighbor {{neighbor}} detail",
    "show ip ospf sham-links",
    "show ip ospf virtual-links",
    "show ip pim bsr-router",
    "show ip pim interface",
    "show ip pim interface detail",
    "show ip pim interface df",
    "show ip pim neighbor",
    "show ip pim rp mapping",
    "show ip pim vrf {{vrf}} bsr-router",
    "show ip pim vrf {{vrf}} interface",
    "show ip pim vrf {{vrf}} interface detail",
    "show ip pim vrf {{vrf}} interface df",
    "show ip pim vrf {{vrf}} neighbor",
    "show ip pim vrf {{vrf}} rp mapping",
    "show ip protocols",
    "show ip protocols vrf {{vrf}}",
    "show ip protocols vrf {{vrf}} | sec rip",
    "show ip protocols | sec rip",
    "show ip rip database",
    "show ip rip database vrf {{vrf}}",
    "show ip route",
    "show ip route summary",
    "show ip route vrf {{vrf}}",
    "show ip route vrf {{vrf}} summary",
    "show ip route vrf {{vrf}} {{protocol}}",
    "show ip route vrf {{vrf}} {{route}}",
    "show ip route {{protocol}}",
    "show ip route {{route}}",
    "show ip static route",
    "show ip static route vrf {{vrf}}",
    "show ip traffic",
    "show ipv6 eigrp interfaces",
    "show ipv6 eigrp interfaces detail",
    "show ipv6 eigrp neighbors",
    "show ipv6 eigrp neighbors detail",
    "show ipv6 interface",
    "show ipv6 interface {{interface}}",
    "show ipv6 mld groups detail",
    "show ipv6 mld interface",
    "show ipv6 mld ssm-map {{group}}",
    "show ipv6 mld vrf {{vrf}} groups detail",
    "show ipv6 mld vrf {{vrf}} interface",
    "show ipv6 mld vrf {{vrf}} ssm-map {{group}}",
    "show ipv6 mroute",
    "show ipv6 mroute vrf {{vrf}}",
    "show ipv6 mroute vrf {{vrf}} {{group}}",
    "show ipv6 mroute vrf {{vrf}} {{group}} {{source}}",
    "show ipv6 mroute vrf {{vrf}} {{group}} {{source}} {{verbose}}",
    "show ipv6 mroute vrf {{vrf}} {{group}} {{verbose}}",
    "show ipv6 mroute vrf {{vrf}} {{verbose}}",
    "show ipv6 mroute {{group}}",
    "show ipv6 mroute {{group}} {{source}}",
    "show ipv6 mroute {{group}} {{source}} {{verbose}}",
    "show ipv6 mroute {{group}} {{verbose}}",
    "show ipv6 mroute {{verbose}}",
    "show ipv6 pim bsr candidate-rp",
    "show ipv6 pim bsr election",
    "show ipv6 pim interface",
    "show ipv6 pim neighbor",
    "show ipv6 pim neighbor detail",
    "show ipv6 pim vrf {{vrf}} bsr candidate-rp",
    "show ipv6 pim vrf {{vrf}} bsr election",
    "show ipv6 pim vrf {{vrf}} interface",
    "show ipv6 pim vrf {{vrf}} neighbor",
    "show ipv6 pim vrf {{vrf}} neighbor detail",
    "show ipv6 prefix-list detail",
    "show ipv6 protocols",
    "show ipv6 protocols vrf {{vrf}}",
    "show ipv6 protocols vrf {{vrf}} | sec rip",
    "show ipv6 protocols | sec rip",
    "show ipv6 rip",
    "show ipv6 rip database",
    "show ipv6 rip vrf {{vrf}}",
    "show ipv6 rip vrf {{vrf}} database",
    "show ipv6 route",
    "show ipv6 route interface {{interface}}",
    "show ipv6 route updated",
    "show ipv6 route vrf {{vrf}}",
    "show ipv6 route vrf {{vrf}} interface {{interface}}",
    "show ipv6 route vrf {{vrf}} updated",
    "show ipv6 route vrf {{vrf}} {{protocol}}",
    "show ipv6 route vrf {{vrf}} {{route}}",
    "show ipv6 route {{protocol}}",
    "show ipv6 route {{route}}",
    "show ipv6 static detail",
    "show ipv6 static vrf {{vrf}} detail",
    "show issu rollback-timer",
    "show issu state detail",
    "show key chain",
    "show l2vpn service all",
    "show l2vpn vfi",
    "show lacp counters",
    "show lacp internal",
    "show lacp neighbor",
    "show lacp neighbor detail",
    "show lacp sys-id",
    "show lacp {{channel_group}} counters",
    "show lacp {{channel_group}} internal",
    "show lacp {{channel_group}} neighbor",
    "show line",
    "show lisp all instance-id {{instance_id}} dynamic-eid detail",
    "show lisp all instance-id {{instance_id}} service {{service}} rloc members",
    "show lisp all instance-id {{instance_id}} service {{service}} smr",
    "show lisp all instance-id {{instance_id}} {{service}} map-cache",
    "show lisp all instance-id {{instance_id}} {{service}} server detail internal",
    "show lisp all instance-id {{instance_id}} {{service}} server summary",
    "show lisp extranet {{extranet_name}} instance-id {{instance_id}}",
    "show lisp instance-id {{instance_id}} {{service}} database",
    "show lisp locator-table vrf {{vrf}} service {{service}} summary",
    "show lisp locator-table {{locator_table}} instance-id {{instance_id}} {{service}} database",
    "show lisp locator-table {{locator_table}} service {{service}} summary",
    "show lisp platform",
    "show lisp service {{service}}",
    "show lisp service {{service}} statistics",
    "show lisp service {{service}} summary",
    "show lisp session",
    "show lisp vrf {{vrf}} session",
    "show lisp {{lisp_id}} extranet {{extranet_name}} instance-id {{instance_id}}",
    "show lisp {{lisp_id}} instance-id {{instance_id}} {{service}} database",
    "show lisp {{lisp_id}} service {{service}}",
    "show lisp {{lisp_id}} service {{service}} statistics",
    "show lisp {{lisp_id}} service {{service}} summary",
    "show lldp",
    "show lldp entry *",
    "show lldp entry {{entry}}",
    "show lldp interface",
    "show lldp interface {{interface}}",
    "show lldp neighbors",
    "show lldp neighbors detail",
    "show lldp traffic",
    "show logging",
    "show logging | exclude {{exclude}}",
    "show logging | include {{include}}",
    "show mac address-table",
    "show mac address-table aging-time",
    "show mac address-table interface {{interface}}",
    "show mac address-table learning",
    "show mac address-table vlan {{vlan}}",
    "show memory statistics",
    "show module",
    "show mpls forwarding-table",
    "show mpls forwarding-table interface tunnel {{tunnelid}}",
    "show mpls forwarding-table vrf {{vrf}}",
    "show mpls forwarding-table {{prefix}}",
    "show mpls forwarding-table {{prefix}} {{mask}} algo {{algo}}",
    "show mpls forwarding-table | sect {{filter}}",
    "show mpls interfaces",
    "show mpls interfaces detail",
    "show mpls interfaces vrf {{vrf}}",
    "show mpls interfaces {{all}}",
    "show mpls interfaces {{interface}}",
    "show mpls interfaces {{interface}} detail",
    "show mpls l2transport vc",
    "show mpls l2transport vc detail",
    "show mpls l2transport vc {{vc_id}} detail",
    "show mpls ldp bindings",
    "show mpls ldp bindings vrf {{vrf}}",
    "show mpls ldp bindings {{all}}",
    "show mpls ldp bindings {{all}} {{detail}}",
    "show mpls ldp capabilities",
    "show mpls ldp capabilities {{all}}",
    "show mpls ldp discovery",
    "show mpls ldp discovery vrf {{vrf}}",
    "show mpls ldp discovery vrf {{vrf}} {{detail}}",
    "show mpls ldp discovery {{all}}",
    "show mpls ldp discovery {{all}} {{detail}}",
    "show mpls ldp discovery {{detail}}",
    "show mpls ldp igp sync",
    "show mpls ldp igp sync interface {{interface}}",
    "show mpls ldp igp sync vrf {{vrf}}",
    "show mpls ldp igp sync {{all}}",
    "show mpls ldp neighbor",
    "show mpls ldp neighbor detail",
    "show mpls ldp neighbor vrf {{vrf}}",
    "show mpls ldp neighbor vrf {{vrf}} detail",
    "show mpls ldp nsr statistics",
    "show mpls ldp parameters",
    "show ntp associations",
    "show ntp associations detail",
    "show ntp config",
    "show ntp status",
    "show pagp counters",
    "show pagp internal",
    "show pagp neighbor",
    "show pagp {{channel_group}} counters",
    "show pagp {{channel_group}} internal",
    "show pagp {{channel_group}} neighbor",
    "show platform",
    "show platform hardware port {{port}} plim statistics",
    "show platform hardware qfp active infrastructure bqs queue output default all",
    "show platform hardware qfp active infrastructure bqs queue output default interface {{interface}}",
    "show platform hardware qfp {{status}} bqs {{slot}} ipm mapping",
    "show platform hardware qfp {{status}} bqs {{slot}} opm mapping",
    "show platform hardware qfp {{status}} bqs {{slot}} {{iotype}} statistics channel all",
    "show platform hardware qfp {{status}} interface if-name {{interface}} statistics",
    "show platform hardware qfp {{status}} statistics drop | exclude _0_",
    "show platform hardware slot {{slot}} plim statistics",
    "show platform hardware slot {{slot}} plim statistics internal",
    "show platform hardware slot {{slot}} serdes statistics",
    "show platform hardware slot {{slot}} serdes statistics internal",
    "show platform hardware subslot {{subslot}} plim statistics",
    "show platform power",
    "show platform software process slot switch active R0 monitor | inc Mem :|Swap:",
    "show platform software status control-processor brief",
    "show policy-map type inspect zone-pair",
    "show policy-map type inspect zone-pair {{zone_pair_name}}",
    "show power inline",
    "show power inline {{interface}}",
    "show processes cpu",
    "show processes cpu history",
    "show processes cpu platform",
    "show processes cpu sorted",
    "show processes cpu sorted {{sort_time}}",
    "show processes cpu sorted {{sort_time}} | exclude {{exclude}}",
    "show processes cpu sorted {{sort_time}} | include {{key_word}}",
    "show processes cpu sorted | exclude {{exclude}}",
    "show processes cpu sorted | include {{key_word}}",
    "show processes memory",
    "show processes memory | exclude {{exclude}}",
    "show processes memory | include {{include}}",
    "show processes memory | section {{section}}",
    "show redundancy",
    "show redundancy application group all",
    "show redundancy application group {{group_id}}",
    "show route-map all",
    "show route-map {{name}}",
    "show service-group state",
    "show service-group stats",
    "show service-group traffic-stats",
    "show service-group traffic-stats {{group}}",
    "show snmp mib",
    "show spanning-tree",
    "show spanning-tree detail",
    "show spanning-tree mst configuration",
    "show spanning-tree mst detail",
    "show spanning-tree mst {{mst}}",
    "show spanning-tree summary",
    "show spanning-tree vlan {{vlan}}",
    "show stack-power, show stack-power budgeting",
    "show standby all",
    "show standby delay",
    "show standby internal",
    "show switch",
    "show switch detail",
    "show users",
    "dir",
    "dir {{directory}}",
    "ping vrf {{vrf}} {{addr}}",
    "ping {{addr}}",
    "ping {{addr}} Extended-data {{extended_data}}",
    "ping {{addr}} source {{source}} repeat {{count}}",
    "show access-lists",
    "show access-lists {{acl}}",
    "show access-session",
    "show access-session interface {{interface}} details",
    "show archive",
    "show archive config differences",
    "show archive config differences {{fileA}}",
    "show archive config differences {{fileA}} {{fileB}}",
    "show archive config incremental-diffs {{fileA}}",
    "show arp",
    "show arp application",
    "show arp summary",
    "show arp vrf {{vrf}}",
    "show arp vrf {{vrf}} {{intf_or_ip}}",
    "show arp {{intf_or_ip}}",
    "show authentication sessions",
    "show authentication sessions interface {{interface}}",
    "show authentication sessions interface {{interface}} details",
    "show authentication sessions interface {{interface}} details switch {{switch}} r0",
    "show bfd neighbors client {{client}} details",
    "show bfd neighbors details",
    "show bfd neighbors interface {{interface}} details",
    "show bfd neighbors ipv4 {{ipv4_address}} details",
    "show bfd neighbors ipv6 {{ipv6_address}} details",
    "show bgp all",
    "show bgp all cluster-ids",
    "show bgp all detail",
    "show bgp all neighbors",
    "show bgp all neighbors {{neighbor}}",
    "show bgp all neighbors {{neighbor}} advertised-routes",
    "show bgp all neighbors {{neighbor}} policy",
    "show bgp all neighbors {{neighbor}} received-routes",
    "show bgp all neighbors {{neighbor}} routes",
    "show bgp all summary",
    "show bgp summary",
    "show bgp vrf {{vrf}} all summary",
    "show bgp vrf {{vrf}} {{route}}",
    "show bgp {{address_family}} all",
    "show bgp {{address_family}} all neighbors",
    "show bgp {{address_family}} all neighbors {{neighbor}}",
    "show bgp {{address_family}} all neighbors {{neighbor}} advertised-routes",
    "show bgp {{address_family}} all neighbors {{neighbor}} received-routes",
    "show bgp {{address_family}} all neighbors {{neighbor}} routes",
    "show bgp {{address_family}} all summary",
    "show bgp {{address_family}} rd {{rd}} summary",
    "show bgp {{address_family}} summary",
    "show bgp {{address_family}} vrf {{vrf}} summary",
    "show bgp {{address_family}} vrf {{vrf}} {{route}}",
    "show bgp {{address_family}} {{route}}",
    "show boot",
    "show bootvar",
    "show bridge-domain",
    "show bridge-domain {{bd_id}}",
    "show bridge-domain | count {{word}}",
    "show cdp neighbors",
    "show cdp neighbors detail",
    "show cdp neighbors {{interface}}",
    "show clock",
    "show configuration lock",
    "show crypto pki certificates",
    "show crypto pki certificates {{trustpoint_name}}",
    "show crypto session",
    "show crypto session detail",
    "show crypto session {{detail}}",
    "show dot1x",
    "show dot1x all count",
    "show dot1x all details",
    "show dot1x all statistics",
    "show dot1x all summary",
    "show environment",
    "show environment | include {{include}}",
    "show errdisable recovery",
    "show etherchannel load-balancing",
    "show etherchannel summary",
    "show etherchannel {{port_channel}} summary",
    "show ethernet service instance detail",
    "show ethernet service instance id {{service_instance_id}} interface {{interface}} detail",
    "show ethernet service instance id {{service_instance_id}} interface {{interface}} stats",
    "show ethernet service instance interface {{interface}} detail",
    "show ethernet service instance interface {{interface}} stats",
    "show ethernet service instance stats",
    "show ethernet service instance summary",
    "show version RP {{rp}} {{status}}",
    "show vlan",
    "show vlan access-map",
    "show vlan filter",
    "show vlan mtu",
    "show vlan remote-span",
    "show vrf",
    "show vrf detail",
    "show vrf detail {{vrf}}",
    "show vrf {{vrf}}",
    "show vtp password",
    "show vtp status",
    "show {{af}} pim neighbor",
    "show {{af}} pim vrf {{vrf}} neighbor",
    "show {{af}} prefix-list detail",
    "show {{af}} rpf vrf {{vrf}} {{mroute}}",
    "show {{af}} rpf {{mroute}}",
    "show version",
]
